### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 2xB** [honkomonk/pyqtgraph_sandbox#1]
Dear Mr. Höfer, if possible I'd like to reuse your function "cmapToColormap". Could you please provide a license (e.g. the MIT license that pyqtgraph is also licensed with)? If that is okay for you, GitHub would also have a feature to automatically add a license file to the repository.
Best regards!

**Comment by 2xB** [comment]
@honkomonk Since I would still like to use this code in an Open Source project and it might even be a good starting point for someone to create a PR to pyqtgraph, I would still be very glad about a MIT-compatible license (e.g. the MIT license itself). Would that be possible? The issue is that "no license" does sadly mean "All rights reserved", see here for more information: https://choosealicense.com/no-permission/

Thank you btw. for that information on matplotlibs colormaps and forwarding that interesting page with video on how Viridis was created over on https://github.com/pyqtgraph/pyqtgraph/pull/1273, that was very interesting and a great talk!

**Comment by honkomonk** [comment]
Hi @2xB, I didn't see your first message.  Thank you for the hint to GitHubs license templates. I just used it to add a MIT license to the files. I'd be happy, if the code is useful to you.

I can offer to integrate it into pyqtgraph and make a PR for it, but this this might take a few days until I have time for that. If you have the time, feel free to do the work.  :)

**Comment by 2xB** [comment]
@honkomonk Perfect, thank you! If you could do such a Pull Request, I think that would be quite great. I currently do not have much time and also have a huge amount of open issues I also would like to write a PR for... Don't worry about time though, this is nothing that has any time constraint. It of course could be handy for probably quite a few people, but there's no reason why this had to be done until tomorrow 😄 

Just if you would plan to do it in half a year, then it could be useful if you open an issue stating that this is an enhancement that was discussed and that you would implement it later, so other people that are interested to help for this topic could talk to you. So feel free to do whatever fits for you!
